export const DEVICE_ACTIVITY_TYPE = {
    CONNECT: "CONNECT",
    DISCONNECT: "DISCONNECT",
    SUSPEND: "SUSPEND",
    QUEUE_FOR_DISCONNECT: "QUEUE_FOR_DISCONNECT",
    QUEUE_FOR_CONNECT: "QUEUE_FOR_CONNECT",
    PING: "PING"    
  };